sudo wget -O "./index.html" "http://tests.ifnmu.edu.ua/index.html"
sudo wget -O "./images" "http://tests.ifnmu.edu.ua/images"
sudo wget -O "./images/preloader-01.gif" "http://tests.ifnmu.edu.ua/images/preloader-01.gif"
sudo wget -O "./images/postbullets.png" "http://tests.ifnmu.edu.ua/images/postbullets.png"
sudo wget -O "./images/footerbullets.png" "http://tests.ifnmu.edu.ua/images/footerbullets.png"
sudo wget -O "./images/footerrssicon.png" "http://tests.ifnmu.edu.ua/images/footerrssicon.png"
sudo wget -O "./images/searchicon.png" "http://tests.ifnmu.edu.ua/images/searchicon.png"
sudo wget -O "./images/postdateicon.png" "http://tests.ifnmu.edu.ua/images/postdateicon.png"
sudo wget -O "./images/postediticon.png" "http://tests.ifnmu.edu.ua/images/postediticon.png"
sudo wget -O "./images/postquote.png" "http://tests.ifnmu.edu.ua/images/postquote.png"
sudo wget -O "./images/blockbullets.png" "http://tests.ifnmu.edu.ua/images/blockbullets.png"
sudo wget -O "./images/page.jpeg" "http://tests.ifnmu.edu.ua/images/page.jpeg"
sudo wget -O "./images/postauthoricon.png" "http://tests.ifnmu.edu.ua/images/postauthoricon.png"
sudo wget -O "./script.responsive.js" "http://tests.ifnmu.edu.ua/script.responsive.js"
sudo wget -O "./script.js" "http://tests.ifnmu.edu.ua/script.js"
sudo wget -O "./style.css" "http://tests.ifnmu.edu.ua/style.css"
sudo wget -O "./style.responsive.css" "http://tests.ifnmu.edu.ua/style.responsive.css"
sudo wget -O "./jquery.js" "http://tests.ifnmu.edu.ua/jquery.js"
sudo wget -O "./krok" "http://tests.ifnmu.edu.ua/krok"
sudo wget -O "./krok/index.html" "http://tests.ifnmu.edu.ua/krok/index.html"
sudo wget -O "./krok/js" "http://tests.ifnmu.edu.ua/krok/js"
sudo wget -O "./krok/js/tems.JS" "http://tests.ifnmu.edu.ua/krok/js/tems.JS"
sudo wget -O "./krok/js/scripts2.JS" "http://tests.ifnmu.edu.ua/krok/js/scripts2.JS"
sudo wget -O "./krok/js/scripts1.JS" "http://tests.ifnmu.edu.ua/krok/js/scripts1.JS"
sudo wget -O "./krok/js/menus.css" "http://tests.ifnmu.edu.ua/krok/js/menus.css"
sudo wget -O "./krok/tests" "http://tests.ifnmu.edu.ua/krok/tests"
sudo wget -O "./krok/tests/index.html" "http://tests.ifnmu.edu.ua/krok/tests/index.html"
sudo wget -O "./krok/tests/js" "http://tests.ifnmu.edu.ua/krok/tests/js"
sudo wget -O "./krok/tests/js/tems.JS" "http://tests.ifnmu.edu.ua/krok/tests/js/tems.JS"
sudo wget -O "./krok/tests/js/scripts1.JS" "http://tests.ifnmu.edu.ua/krok/tests/js/scripts1.JS"
sudo wget -O "./krok/tests/js/menus.css" "http://tests.ifnmu.edu.ua/krok/tests/js/menus.css"
sudo wget -O "./krok/tests/IMG" "http://tests.ifnmu.edu.ua/krok/tests/IMG"
sudo wget -O "./krok/tests/IMG/an3_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an3_03.gif"
sudo wget -O "./krok/tests/IMG/an1_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an1_03.gif"
sudo wget -O "./krok/tests/IMG/an5_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an5_03.gif"
sudo wget -O "./krok/tests/IMG/an2_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an2_03.gif"
sudo wget -O "./krok/tests/IMG/qu_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/qu_03.gif"
sudo wget -O "./krok/tests/IMG/an4_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an4_03.gif"
sudo wget -O "./krok/tests/IMG/an6_03.gif" "http://tests.ifnmu.edu.ua/krok/tests/IMG/an6_03.gif"
sudo wget -O "./krok/IMG" "http://tests.ifnmu.edu.ua/krok/IMG"
sudo wget -O "./krok/IMG/an3_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an3_03.gif"
sudo wget -O "./krok/IMG/an1_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an1_03.gif"
sudo wget -O "./krok/IMG/an5_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an5_03.gif"
sudo wget -O "./krok/IMG/an2_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an2_03.gif"
sudo wget -O "./krok/IMG/qu_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/qu_03.gif"
sudo wget -O "./krok/IMG/an4_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an4_03.gif"
sudo wget -O "./krok/IMG/an6_03.gif" "http://tests.ifnmu.edu.ua/krok/IMG/an6_03.gif"
sudo wget -O "./krok/DATA" "http://tests.ifnmu.edu.ua/krok/DATA"
sudo wget -O "./krok/DATA/DUS1" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1"
sudo wget -O "./krok/DATA/DUS1/Krok_4" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_10.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_10.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_9.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_9.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_11.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_11.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_8.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_8.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_7.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_7.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_3.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_3.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_2.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_2.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_6.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_6.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_1.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_1.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_5.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_5.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/title.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/title.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_4.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_4.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_12.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_12.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_4/roz_13.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_4/roz_13.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2"
sudo wget -O "./krok/DATA/DUS1/Krok_2/roz_3.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/roz_3.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2/roz_2.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/roz_2.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2/roz_1.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/roz_1.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2/roz_5.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/roz_5.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2/title.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/title.JS"
sudo wget -O "./krok/DATA/DUS1/Krok_2/roz_4.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1/Krok_2/roz_4.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_10.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_10.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_9.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_9.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_11.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_11.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_8.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_8.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_7.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_7.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_3.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_3.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_2.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_2.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_6.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_6.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_1.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_1.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_5.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_5.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/title.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/title.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_4.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_4.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_12.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_12.JS"
sudo wget -O "./krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_13.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS1_exampl copy/Krok_4_exam/roz_13.JS"
sudo wget -O "./krok/DATA/DUS4" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4"
sudo wget -O "./krok/DATA/DUS4/Krok_1" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1"
sudo wget -O "./krok/DATA/DUS4/Krok_1/roz_3.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/roz_3.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_1/roz_2.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/roz_2.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_1/roz_1.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/roz_1.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_1/roz_5.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/roz_5.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_1/title.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/title.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_1/roz_4.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_1/roz_4.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_4" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_4"
sudo wget -O "./krok/DATA/DUS4/Krok_4/roz_3.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_4/roz_3.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_4/roz_2.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_4/roz_2.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_4/roz_1.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_4/roz_1.JS"
sudo wget -O "./krok/DATA/DUS4/Krok_4/title.JS" "http://tests.ifnmu.edu.ua/krok/DATA/DUS4/Krok_4/title.JS"